[package]
name = "outline-core"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/wyh2001/outline"

[features]
default = ["cli"]
cli = ["clap", "vectorizer-vtracer"]
vectorizer-vtracer = ["dep:vtracer", "dep:visioncortex"]

[lib]
name = "outline"
path = "src/lib.rs"

[dependencies]
image = "0.25.8"
ort = "2.0.0-rc.10"
vtracer = { version = "0.6.4", optional = true }
ndarray = "0.16.1"
visioncortex = { version = "0.8.8", optional = true }
imageproc = "0.25.0"
thiserror = "2"
clap = { version = "4", features = ["derive"], optional = true }

[[bin]]
name = "outline"
path = "src/main.rs"
required-features = ["cli"]

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
